blank_issues_enabled: false
contact_links:
- name: 💬🤷💻🤦 MatterMost
  url: https://mm.openiap.io/
  about: Please go here for usage help and general questions, use only github is only for bug reports.
- name: 🤷💻🤦 Slack
  url: https://slack.openrpa.dk/
  about: Please go here for usage help and general questions, use only github is only for bug reports.
