blank_issues_enabled: false
contact_links:
- name: 🤷💻🤦 MatterMost
  url: https://mm.openiap.io/
  about: Please ask typical Q&A here
- name: 🤷💻🤦 Slack
  url: https://slack.openrpa.dk/
  about: Please ask typical Q&A here
